apiVersion: apps/v1
kind: Deployment
metadata:
  name: redeye
spec:
  template:
    spec:
      volumes:
        - name: redeye-files
          hostPath:
            path: /disk1/redeye/files-htb
        - name: redeye-db
          hostPath:
            path: /disk1/redeye/db-htb
      containers:
        - name: reddeye
          env:
            - name: NEO4J_DATABASE
              value: RedEyeWorkHTB
